# Generated by Django 3.2 on 2021-04-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0012_alter_orderitem_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
