# Generated by Django 3.2 on 2021-04-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0013_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
